backend:
  name: github
  repo: sarckk/personal-site


local_backend: true

media_folder: content/assets
public_folder: /
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: content/blog
    extension: mdx
    format: frontmatter
    create: true
    fields:
      - { label: Title, name: title }
      - { label: Description, name: description }
      - {
          label: Date,
          name: date,
          widget: datetime,
          dateFormat: "MMM DD, YYYY",
          timeFormat: false,
          format: "YYYY-MM-DD",
        }
      - { label: Hidden, name: is_hidden, widget: boolean, default: false }
      - { label: Image, name: featuredImage, widget: image }
      - { label: Body, name: body, widget: markdown }
