backend:
  name: github
  repo: sarckk/personal-site

media_folder: content/assets
public_folder: /
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: content/blog
    extension: mdx
    format: frontmatter
    create: true
    fields:
      - {label: "Template Key", name: templateKey, widget: "hidden", default: "blog-post"}
      - { label: Title, name: title }
      - { label: Description, name: description }
      - {
          label: Date,
          name: date,
          widget: datetime,
          dateFormat: "MMM DD, YYYY",
          timeFormat: false,
          format: "YYYY-MM-DD",
        }
      - { label: Hidden, name: is_hidden, widget: boolean, default: false }
      - { label: Image, name: featuredImage, widget: image }
      - { label: Body, name: body, widget: markdown }
  - name: books
    label: "Book Reviews"
    folder: content/books
    extension: mdx
    format: frontmatter
    create: true
    fields:
      - {label: "Template Key", name: templateKey, widget: "hidden", default: "book-review"}
      - { label: "Book Title", name: title }
      - { label: Authors, name: authors }
      - { label: Summary, name: summary }
      - { label: ISBN, name: isbn}
      - { label: Image, name: backupImage, widget: image}
      - { label: "Use Backup", name: use_backup, widget: boolean, default: false }
      - { label: Hidden, name: is_hidden, widget: boolean, default: false }
      - { label: Body, name: body, widget: markdown }
