backend:
  name: github
  repo: sarckk/personal-site

media_folder: content/assets
public_folder: assets
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { label: Title, name: title }
      - { label: Description, name: description }
      - {
          label: Date,
          name: date,
          widget: datetime,
          default: "",
          dateFormat: "DD.MM.YYYY",
          timeFormat: "HH:mm",
          format: "LLL",
        }
      - { label: Hidden, name: is_hidden, widget: boolean, default: false }
      - { label: Image, name: featuredImage, widget: image }
      - { label: Body, name: body, widget: markdown }
