backend:
  name: github
  repo: sarckk/personal-site
 

media_folder: content/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { label: "Published Date", name: date, label: Date, widget: date }
      - { label: "Title", name: title, label: Title }
      - { label: "Description", name: description, label: Description }
      - {label: "Hidden", name: is_hidden, widget: "boolean", default: false}
      - { label: "Featured Image", name: featuredImage, widget: image}
      - { label: "Body", name: body, label: Body, widget: markdown }
